Repository open-sauced/docs, pull requests merged in 2023-09, with the labels that each got.

#155 feat: update docs to be more specific and reflect current features
  .github/workflows/release.yml
  docs/community/100-days-of-oss.md
  docs/community/highlights.md
  docs/community/insights.md
  docs/community/welcome-to-the-community.md
  static/img/highlight.svg
Labels: 📝 documentation

#137 docs: adding a gif of doing a highlight on the website
  docs/community/highlights.md
  static/gif/highlight.gif
Labels: 💡 feature

#161 fix: text to be more concise #160
  docs/community/100-days-of-oss.md
Labels: 📝 documentation

#158 docs: adding explainer page about Dev card
  docs/community/dev-card.md
  sidebars.js
  static/img/a-dev-card.png
Labels: 💡 feature, chore
