Repository open-sauced/docs, pull requests merged in 2023-10, with the labels that each got.

#175 fix: add parallel structure
  docs/community/100-days-of-oss.md
  docs/community/faqs.md
  docs/community/highlights.md
Labels: 📝 documentation, chore

#184 feat: terminology added
  docs/contributing/introduction-to-contributing.md
  docs/maintainers/setting-up-a-new-repository.md
  docs/technical/resolve-merge-conflicts.md
Labels: 📝 documentation

#196 feat: add algolia search functionality to docs
  .gitignore
  docusaurus.config.js
Labels: awaiting review

#197 docs: adding section for the Hot OpenSauced Project
  docs/community/hot-opensauced.md
  sidebars.js
  static/img/popular-repos-hot-opensauced.png
  static/img/upvoted-repos-hot-opensauced.png
Labels: 📝 documentation

#193 feat: Add lists to docs
  docs/community/lists.md
  sidebars.js
  static/img/lists-page.svg
Labels: 📝 documentation
