Repository open-sauced/docs, pull requests merged in 2023-08, with the labels that each got.

#135 docs: revise information about templates
  docs/community/100-days-of-oss.md
Labels: 📝 documentation

#144 fix: Incorrect Link Destination in Documentation
  docs/community/welcome-to-the-community.md
Labels: awaiting review

#148 fix: Documentation Link Misdirection
  docs/community/100-days-of-oss.md
Labels: 📝 documentation

#138 docs: adding an explainer page and GIF on insight pages
  docs/community/insight-pages.md
  sidebars.js
  static/gif/insight-page-demo.gif
Labels: 💡 feature

#151 feat: add explainer page about PR velocity
  docs/community/pr-velocity.md
  static/img/pr-velocity-example.png
Labels: 📝 documentation
